events { worker_connections 1024; }

http {
    upstream myapp {
        # 'web-app' matches the service name in docker-compose.yml
        server web-app:6969;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://myapp;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
